/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author rambo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        menuOpc = new javax.swing.JPanel();
        registerLabelMenuOpc = new javax.swing.JLabel();
        deleteLabelMenuOpc = new javax.swing.JLabel();
        modifyLabelMenuOpc = new javax.swing.JLabel();
        searchLabelMenuOpc = new javax.swing.JLabel();
        showLabelMenuOpc = new javax.swing.JLabel();
        spliter1 = new javax.swing.JLabel();
        spliter2 = new javax.swing.JLabel();
        spliter3 = new javax.swing.JLabel();
        spliter4 = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        welcomeTab = new javax.swing.JPanel();
        registerTab = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idValue = new javax.swing.JSpinner();
        nameLabel = new javax.swing.JLabel();
        nameValue = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderValue = new javax.swing.JComboBox<>();
        ageLabel = new javax.swing.JLabel();
        ageValue = new javax.swing.JSpinner();
        addressLabel = new javax.swing.JLabel();
        addressValue = new javax.swing.JTextField();
        vehicleLabel = new javax.swing.JLabel();
        vehicleButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        typeValue = new javax.swing.JComboBox<>();
        idEmployeeLabel = new javax.swing.JLabel();
        idEmployeeValue = new javax.swing.JSpinner();
        salaryLabel = new javax.swing.JLabel();
        salaryValue = new javax.swing.JSpinner();
        idCustomerLabel = new javax.swing.JLabel();
        idCustomerValue = new javax.swing.JSpinner();
        dateLabel = new javax.swing.JLabel();
        dateValue = new javax.swing.JTextField();
        vipLabel = new javax.swing.JLabel();
        vipValue = new javax.swing.JToggleButton();
        registerButton = new javax.swing.JButton();
        deleteTab = new javax.swing.JPanel();
        modifyTab = new javax.swing.JPanel();
        searchTab = new javax.swing.JPanel();
        showTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuOpc.setBackground(new java.awt.Color(153, 153, 153));
        menuOpc.setForeground(new java.awt.Color(153, 153, 153));
        menuOpc.setLayout(new java.awt.GridBagLayout());

        registerLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
        registerLabelMenuOpc.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        registerLabelMenuOpc.setForeground(new java.awt.Color(0, 0, 0));
        registerLabelMenuOpc.setText("REGISTER");
        registerLabelMenuOpc.setOpaque(true);
        registerLabelMenuOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMenuOpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerLabelMenuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerLabelMenuOpcMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(registerLabelMenuOpc, gridBagConstraints);

        deleteLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
        deleteLabelMenuOpc.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        deleteLabelMenuOpc.setForeground(new java.awt.Color(0, 0, 0));
        deleteLabelMenuOpc.setText("DELETE");
        deleteLabelMenuOpc.setOpaque(true);
        deleteLabelMenuOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLabelMenuOpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLabelMenuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLabelMenuOpcMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(deleteLabelMenuOpc, gridBagConstraints);

        modifyLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
        modifyLabelMenuOpc.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        modifyLabelMenuOpc.setForeground(new java.awt.Color(0, 0, 0));
        modifyLabelMenuOpc.setText("MODIFY");
        modifyLabelMenuOpc.setOpaque(true);
        modifyLabelMenuOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyLabelMenuOpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyLabelMenuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyLabelMenuOpcMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(modifyLabelMenuOpc, gridBagConstraints);

        searchLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
        searchLabelMenuOpc.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        searchLabelMenuOpc.setForeground(new java.awt.Color(0, 0, 0));
        searchLabelMenuOpc.setText("SEARCH");
        searchLabelMenuOpc.setOpaque(true);
        searchLabelMenuOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchLabelMenuOpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchLabelMenuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchLabelMenuOpcMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(searchLabelMenuOpc, gridBagConstraints);

        showLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
        showLabelMenuOpc.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        showLabelMenuOpc.setForeground(new java.awt.Color(0, 0, 0));
        showLabelMenuOpc.setText("SHOW");
        showLabelMenuOpc.setOpaque(true);
        showLabelMenuOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showLabelMenuOpcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showLabelMenuOpcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showLabelMenuOpcMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(showLabelMenuOpc, gridBagConstraints);

        spliter1.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        spliter1.setForeground(new java.awt.Color(51, 51, 51));
        spliter1.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(spliter1, gridBagConstraints);

        spliter2.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        spliter2.setForeground(new java.awt.Color(51, 51, 51));
        spliter2.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(spliter2, gridBagConstraints);

        spliter3.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        spliter3.setForeground(new java.awt.Color(51, 51, 51));
        spliter3.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(spliter3, gridBagConstraints);

        spliter4.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        spliter4.setForeground(new java.awt.Color(51, 51, 51));
        spliter4.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 35);
        menuOpc.add(spliter4, gridBagConstraints);

        panelPrincipal.add(menuOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 80));

        welcomeTab.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout welcomeTabLayout = new javax.swing.GroupLayout(welcomeTab);
        welcomeTab.setLayout(welcomeTabLayout);
        welcomeTabLayout.setHorizontalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        welcomeTabLayout.setVerticalGroup(
            welcomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("WELCOME", welcomeTab);

        registerTab.setBackground(new java.awt.Color(204, 204, 204));
        registerTab.setLayout(new java.awt.GridBagLayout());

        idLabel.setBackground(new java.awt.Color(255, 255, 255));
        idLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("ID");
        idLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        idLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(60, 0, 10, 0);
        registerTab.add(idLabel, gridBagConstraints);

        idValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        idValue.setBorder(null);
        idValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(idValue, gridBagConstraints);

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameLabel.setText("NAME");
        nameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nameLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        registerTab.add(nameLabel, gridBagConstraints);

        nameValue.setBackground(new java.awt.Color(204, 204, 204));
        nameValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        nameValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        nameValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(nameValue, gridBagConstraints);

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderLabel.setText("GENDER");
        genderLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        genderLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        registerTab.add(genderLabel, gridBagConstraints);

        genderValue.setBackground(new java.awt.Color(0, 0, 0));
        genderValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        genderValue.setForeground(new java.awt.Color(255, 255, 255));
        genderValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE", "MUJER" }));
        genderValue.setBorder(null);
        genderValue.setOpaque(true);
        genderValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(genderValue, gridBagConstraints);

        ageLabel.setBackground(new java.awt.Color(255, 255, 255));
        ageLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(0, 0, 0));
        ageLabel.setText("AGE");
        ageLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ageLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        registerTab.add(ageLabel, gridBagConstraints);

        ageValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        ageValue.setBorder(null);
        ageValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(ageValue, gridBagConstraints);

        addressLabel.setBackground(new java.awt.Color(255, 255, 255));
        addressLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(0, 0, 0));
        addressLabel.setText("ADDRESS");
        addressLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addressLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        registerTab.add(addressLabel, gridBagConstraints);

        addressValue.setBackground(new java.awt.Color(204, 204, 204));
        addressValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        addressValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        addressValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(addressValue, gridBagConstraints);

        vehicleLabel.setBackground(new java.awt.Color(255, 255, 255));
        vehicleLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        vehicleLabel.setForeground(new java.awt.Color(0, 0, 0));
        vehicleLabel.setText("VEHICLE");
        vehicleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        vehicleLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        registerTab.add(vehicleLabel, gridBagConstraints);

        vehicleButton.setBackground(new java.awt.Color(0, 0, 0));
        vehicleButton.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        vehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        vehicleButton.setText("ADD VEHICLE");
        vehicleButton.setBorder(null);
        vehicleButton.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        registerTab.add(vehicleButton, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(0, 0, 0));
        typeLabel.setText("TYPE");
        typeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        typeLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(60, 200, 10, 0);
        registerTab.add(typeLabel, gridBagConstraints);

        typeValue.setBackground(new java.awt.Color(0, 0, 0));
        typeValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        typeValue.setForeground(new java.awt.Color(255, 255, 255));
        typeValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPLOYEE", "CUSTOMER" }));
        typeValue.setBorder(null);
        typeValue.setOpaque(true);
        typeValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(typeValue, gridBagConstraints);

        idEmployeeLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idEmployeeLabel.setForeground(new java.awt.Color(0, 0, 0));
        idEmployeeLabel.setText("ID EMPLOYEE");
        idEmployeeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        idEmployeeLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 200, 5, 0);
        registerTab.add(idEmployeeLabel, gridBagConstraints);

        idEmployeeValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idEmployeeValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        idEmployeeValue.setBorder(null);
        idEmployeeValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(idEmployeeValue, gridBagConstraints);

        salaryLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        salaryLabel.setForeground(new java.awt.Color(0, 0, 0));
        salaryLabel.setText("SALARY");
        salaryLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        salaryLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 200, 5, 0);
        registerTab.add(salaryLabel, gridBagConstraints);

        salaryValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        salaryValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        salaryValue.setBorder(null);
        salaryValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(salaryValue, gridBagConstraints);

        idCustomerLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idCustomerLabel.setForeground(new java.awt.Color(0, 0, 0));
        idCustomerLabel.setText("ID CUSTOMER");
        idCustomerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        idCustomerLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 200, 5, 0);
        registerTab.add(idCustomerLabel, gridBagConstraints);

        idCustomerValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        idCustomerValue.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        idCustomerValue.setBorder(null);
        idCustomerValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(idCustomerValue, gridBagConstraints);

        dateLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateLabel.setText("DATE");
        dateLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dateLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 200, 5, 0);
        registerTab.add(dateLabel, gridBagConstraints);

        dateValue.setBackground(new java.awt.Color(204, 204, 204));
        dateValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        dateValue.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 0, 0)));
        dateValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(dateValue, gridBagConstraints);

        vipLabel.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        vipLabel.setForeground(new java.awt.Color(0, 0, 0));
        vipLabel.setText("VIP");
        vipLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        vipLabel.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 200, 5, 0);
        registerTab.add(vipLabel, gridBagConstraints);

        vipValue.setBackground(new java.awt.Color(0, 0, 0));
        vipValue.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        vipValue.setForeground(new java.awt.Color(255, 255, 255));
        vipValue.setText("IS VIP?");
        vipValue.setBorder(null);
        vipValue.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 200, 10, 0);
        registerTab.add(vipValue, gridBagConstraints);

        registerButton.setBackground(new java.awt.Color(0, 0, 0));
        registerButton.setFont(new java.awt.Font("Anta", 0, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("REGISTER");
        registerButton.setBorder(null);
        registerButton.setPreferredSize(new java.awt.Dimension(200, 50));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 0);
        registerTab.add(registerButton, gridBagConstraints);

        tabbedPanel.addTab("REGISTER", registerTab);

        deleteTab.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout deleteTabLayout = new javax.swing.GroupLayout(deleteTab);
        deleteTab.setLayout(deleteTabLayout);
        deleteTabLayout.setHorizontalGroup(
            deleteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        deleteTabLayout.setVerticalGroup(
            deleteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("DELETE", deleteTab);

        modifyTab.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout modifyTabLayout = new javax.swing.GroupLayout(modifyTab);
        modifyTab.setLayout(modifyTabLayout);
        modifyTabLayout.setHorizontalGroup(
            modifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        modifyTabLayout.setVerticalGroup(
            modifyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("MODIFY", modifyTab);

        searchTab.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("SEARCH", searchTab);

        showTab.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout showTabLayout = new javax.swing.GroupLayout(showTab);
        showTab.setLayout(showTabLayout);
        showTabLayout.setHorizontalGroup(
            showTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        showTabLayout.setVerticalGroup(
            showTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("SHOW", showTab);

        panelPrincipal.add(tabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1500, 940));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerLabelMenuOpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMenuOpcMouseClicked
        tabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_registerLabelMenuOpcMouseClicked

    private void deleteLabelMenuOpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMenuOpcMouseClicked
        tabbedPanel.setSelectedIndex(2);
    }//GEN-LAST:event_deleteLabelMenuOpcMouseClicked

    private void modifyLabelMenuOpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyLabelMenuOpcMouseClicked
        tabbedPanel.setSelectedIndex(3);
    }//GEN-LAST:event_modifyLabelMenuOpcMouseClicked

    private void searchLabelMenuOpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMenuOpcMouseClicked
        tabbedPanel.setSelectedIndex(4);
    }//GEN-LAST:event_searchLabelMenuOpcMouseClicked

    private void showLabelMenuOpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showLabelMenuOpcMouseClicked
        tabbedPanel.setSelectedIndex(5);
    }//GEN-LAST:event_showLabelMenuOpcMouseClicked

    private void registerLabelMenuOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMenuOpcMouseEntered
        registerLabelMenuOpc.setBackground(new java.awt.Color(102, 102, 102));

    }//GEN-LAST:event_registerLabelMenuOpcMouseEntered

    private void registerLabelMenuOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMenuOpcMouseExited
        registerLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_registerLabelMenuOpcMouseExited

    private void deleteLabelMenuOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMenuOpcMouseEntered
        deleteLabelMenuOpc.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_deleteLabelMenuOpcMouseEntered

    private void deleteLabelMenuOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLabelMenuOpcMouseExited
        deleteLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_deleteLabelMenuOpcMouseExited

    private void modifyLabelMenuOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyLabelMenuOpcMouseEntered
        modifyLabelMenuOpc.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_modifyLabelMenuOpcMouseEntered

    private void modifyLabelMenuOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyLabelMenuOpcMouseExited
        modifyLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_modifyLabelMenuOpcMouseExited

    private void searchLabelMenuOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMenuOpcMouseEntered
        searchLabelMenuOpc.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_searchLabelMenuOpcMouseEntered

    private void searchLabelMenuOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchLabelMenuOpcMouseExited
        searchLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_searchLabelMenuOpcMouseExited

    private void showLabelMenuOpcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showLabelMenuOpcMouseEntered
        showLabelMenuOpc.setBackground(new java.awt.Color(102, 102, 102));
    }//GEN-LAST:event_showLabelMenuOpcMouseEntered

    private void showLabelMenuOpcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showLabelMenuOpcMouseExited
        showLabelMenuOpc.setBackground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_showLabelMenuOpcMouseExited

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressValue;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageValue;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateValue;
    private javax.swing.JLabel deleteLabelMenuOpc;
    private javax.swing.JPanel deleteTab;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> genderValue;
    private javax.swing.JLabel idCustomerLabel;
    private javax.swing.JSpinner idCustomerValue;
    private javax.swing.JLabel idEmployeeLabel;
    private javax.swing.JSpinner idEmployeeValue;
    private javax.swing.JLabel idLabel;
    private javax.swing.JSpinner idValue;
    private javax.swing.JPanel menuOpc;
    private javax.swing.JLabel modifyLabelMenuOpc;
    private javax.swing.JPanel modifyTab;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameValue;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerLabelMenuOpc;
    private javax.swing.JPanel registerTab;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JSpinner salaryValue;
    private javax.swing.JLabel searchLabelMenuOpc;
    private javax.swing.JPanel searchTab;
    private javax.swing.JLabel showLabelMenuOpc;
    private javax.swing.JPanel showTab;
    private javax.swing.JLabel spliter1;
    private javax.swing.JLabel spliter2;
    private javax.swing.JLabel spliter3;
    private javax.swing.JLabel spliter4;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> typeValue;
    private javax.swing.JButton vehicleButton;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JLabel vipLabel;
    private javax.swing.JToggleButton vipValue;
    private javax.swing.JPanel welcomeTab;
    // End of variables declaration//GEN-END:variables
}
